import { Button, Carousel, DarkThemeToggle, Footer, Modal } from "flowbite-react";
import Head from "next/head";
import { useState } from "react";
import { BiBuoy } from "react-icons/bi";
import {
  BsDribbble,
  BsFacebook,
  BsGithub,
  BsInstagram,
  BsTwitter,
} from "react-icons/bs";
import {
  HiArrowSmRight,
  HiChartPie,
  HiPlus,
  HiTable,
  HiViewBoards,
} from "react-icons/hi";
import Sidebar from "../components/sidebar";
import { SidebarProvider } from "../context/SidebarContext";

export default function Index(): JSX.Element {
  return (
    <>
      <Head>
        <title>Feel Good Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SidebarProvider>
        <div className="flex dark:bg-gray-900 h-screen w-screen">
          <main className="order-2 mx-4 mt-4 mb-24 flex-[1_0_16rem]">
            <HomePage />
          </main>
          <div className="order-1">
            <ActualSidebar />
          </div>
        </div>
      </SidebarProvider>
    </>
  );
}

function ActualSidebar(): JSX.Element {
  return (
    <Sidebar>
      <Sidebar.Items>
        <Sidebar.ItemGroup>
          <Sidebar.Item href="#" icon={HiChartPie}>
            Dashboard
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiPlus}>
            AddUser
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiArrowSmRight}>
            Sign In
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiTable}>
            Sign Up
          </Sidebar.Item>
        </Sidebar.ItemGroup>
        <Sidebar.ItemGroup>
          <Sidebar.Item href="#" icon={HiChartPie}>
            Upgrade to Pro
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiViewBoards}>
            Settings
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={BiBuoy}>
            Help
          </Sidebar.Item>
          <DarkThemeToggle />
        </Sidebar.ItemGroup>
      </Sidebar.Items>
    </Sidebar>
  );
}

function HomePage(): JSX.Element {
  return (
    <>
      <section>
        <header>
          <h1 className="mb-6 text-5xl font-extrabold dark:text-gray-200">
            Feel Good Inc
          </h1>
          <p className="mb-6 text-2xl font-extrabold dark:text-gray-200">
            Feel Good Inc
          </p>
        </header>
      </section>
      <section>
        <header>
          <h2 className="mt-9 mb-3 text-4xl font-bold dark:text-gray-200">
            Top Events
          </h2>
        </header>
        <CarouselExample />
      </section>
      <section>
        <header>
          <h2 className="mt-9 mb-3 text-4xl font-bold dark:text-gray-200">
            Footer
          </h2>
        </header>
        <ModalNewElement />
      </section>
    </>
  );
}

function CarouselExample(): JSX.Element {
  return (
    <div className="h-56 sm:h-64 xl:h-80 2xl:h-96">
      <Carousel>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
      </Carousel>
    </div>
  );
}
function ModalNewElement(): JSX.Element {
  const [isOpen, setOpen] = useState(false);

 return (
      <><Button onClick={() => setOpen(true)}>Set new events</Button><Modal show={isOpen} onClose={() => setOpen(false)}>
     <Modal.Header>CreateEvent</Modal.Header>
     <Modal.Body>
       <div className="space-y-3">
         
         <div className="flex space-x-12 ">
                       <label htmlFor="name" className="py-2  block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Name</label>
                       <input type="text" name="password" id="password"  className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " required></input>
                   </div>
                   <div className="flex space-x-12 ">
                       <label htmlFor="email" className=" py-2 block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
                       <input type="email" name="email" id="email" className=" bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " required></input>
                   </div>
                   <div className="flex space-x-14 ">
                       <label htmlFor="date" className=" py-2 block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Date</label>
                       <input type="date" name="date" id="date"  className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " required></input>
                   </div >
                   <div className="flex space-x-11 ">
                       <label htmlFor="where" className=" py-2 block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Where</label>
                       <input type="text" name="name" id="name" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " required></input>
                   </div>
                   <div className="flex  space-x-1">
                       <label htmlFor="competence" className=" py-2 block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Competence </label>
                       <input type="text" name="competence " id="competence " className="  bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " ></input>
                   </div>
                  
                   <div className="flex space-x-12">   
                       <label htmlFor="photo" className=" py-2 block  mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">Background photo</label>
                       <input type="file" name="photo" id="photo" className=" px-5" ></input>
                  </div>
                   
                   <div className="flex ">
                       <label htmlFor="type" className=" py-2  block mb-1 text-sm font-medium text-gray-900 dark:text-gray-300">How many people</label>
                       <input type="text" name="type" id="type" className="clear-left bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " ></input>
                   </div>
                   <div className="flex space-x-2">
                       <label htmlFor="description" className="py-10 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Description</label>
                       <textarea  name="description" id="description"  rows="5"  className="bg-gray-50 border width=20% border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500" ></textarea>
                   </div>
        
       </div>
     </Modal.Body>
     <Modal.Footer>
       <Button onClick={() => setOpen(false)}>Submit</Button>
      
     </Modal.Footer>
   </Modal></> 
 
 );
}

function FooterExample(): JSX.Element {
  return (
    <Footer container>
      <div className="w-full sm:flex sm:items-center sm:justify-between">
        <Footer.Copyright href="#" by="Proteus Belivers" year={2022} />
        <div className="mt-4 flex space-x-6 sm:mt-0 sm:justify-center">
          <Footer.Icon href="#" icon={BsFacebook} />
          <Footer.Icon href="#" icon={BsInstagram} />
          <Footer.Icon href="#" icon={BsTwitter} />
          <Footer.Icon href="#" icon={BsGithub} />
          <Footer.Icon href="#" icon={BsDribbble} />
        </div>
      </div>
    </Footer>
  );
}



