import {Carousel, Footer} from "flowbite-react";
import Head from "next/head";
import { BiBuoy } from "react-icons/bi";
import {
  BsDribbble,
  BsFacebook,
  BsGithub,
  BsInstagram,
  BsTwitter,
} from "react-icons/bs";
import {
  HiArrowSmRight,
  HiChartPie,
  HiPlus,
  HiTable,
  HiViewBoards,
} from "react-icons/hi";
import Sidebar from "../components/sidebar";
import { SidebarProvider } from "../context/SidebarContext";
import Header from "../components/header";

export default function Index(): JSX.Element {
  return (
    <>
      <Head>
        <title>Feel Good Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SidebarProvider>
        <Header/>
        <div className="flex dark:bg-gray-900 h-screen w-screen">
          <main className="order-2 mx-4 mt-4 mb-24 flex-[1_0_16rem]">
            <HomePage />
          </main>
          <div className="order-1">
            <ActualSidebar />
          </div>
        </div>
      </SidebarProvider>
    </>
  );
}

function ActualSidebar(): JSX.Element {
  return (
    <Sidebar>
      <Sidebar.Items>
        <Sidebar.ItemGroup>
          <Sidebar.Item href="#" icon={HiChartPie}>
            Dashboard
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiPlus}>
            AddUser
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiArrowSmRight}>
            Sign In
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiTable}>
            Sign Up
          </Sidebar.Item>
        </Sidebar.ItemGroup>
        <Sidebar.ItemGroup>
          <Sidebar.Item href="#" icon={HiChartPie}>
            Upgrade to Pro
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={HiViewBoards}>
            Settings
          </Sidebar.Item>
          <Sidebar.Item href="#" icon={BiBuoy}>
            Help
          </Sidebar.Item>
        </Sidebar.ItemGroup>
      </Sidebar.Items>
    </Sidebar>
  );
}

function HomePage(): JSX.Element {
  return (
    <>
      <section>
        <header>
          <h1 className="mb-6 text-5xl font-extrabold dark:text-gray-200">
            Feel Good Inc
          </h1>
          <p className="mb-6 text-2xl font-extrabold dark:text-gray-200">
            Feel Good Inc
          </p>
        </header>
      </section>
      <section>
        <header>
          <h2 className="mt-9 mb-3 text-4xl font-bold dark:text-gray-200">
            Top Events
          </h2>
        </header>
        <CarouselExample />
      </section>
      <section>
        <header>
          <h2 className="mt-9 mb-3 text-4xl font-bold dark:text-gray-200">
            Footer
          </h2>
        </header>
        <FooterExample />
      </section>
    </>
  );
}

function CarouselExample(): JSX.Element {
  return (
    <div className="h-56 sm:h-64 xl:h-80 2xl:h-96">
      <Carousel>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
        <div className="flex content-center justify-center h-max">
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
          />
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            className="w-1/5 px-2"
            alt="..."
            src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
          />
        </div>
      </Carousel>
    </div>
  );
}

function FooterExample(): JSX.Element {
  return (
    <Footer container>
      <div className="w-full sm:flex sm:items-center sm:justify-between">
        <Footer.Copyright href="#" by="Proteus Belivers" year={2022} />
        <div className="mt-4 flex space-x-6 sm:mt-0 sm:justify-center">
          <Footer.Icon href="#" icon={BsFacebook} />
          <Footer.Icon href="#" icon={BsInstagram} />
          <Footer.Icon href="#" icon={BsTwitter} />
          <Footer.Icon href="#" icon={BsGithub} />
          <Footer.Icon href="#" icon={BsDribbble} />
        </div>
      </div>
    </Footer>
  );
}
